### PR TITLE
Speed up BBox calculation x2 times

### PR DESCRIPTION
**Pull request by Oxicid**
Functions min and max are replaced by corresponding operators - which leads to optimization.  Also, calls to vector properties (vec.x and vec.y) are reduced, saving values in float type in advance (yes, calls to vector fields are equivalent to function calls, although they are executed quickly, but in a particular case slightly slows down the calculation).

### CODE REVIEW

**Comment by Oxicid** [comment]
The most important thing is to replace the current implementation of the function of finding uv islands. I have such a function, and it works 80-100 times faster, and what is not unimportant works in sync mode.
I will add it next ;)

**Comment by franMarz** [comment]
Good catch. But please don't add not fully functional code to the pull request, neither add code not aligned with the purpose or title of the pull request to it. Otherwise, there is no way we know whether the code is ready for a review, unless you add "WIP" to the title. I wanted to commit the BBox changes but I can't now.

**Comment by Oxicid** [comment]
I knew it was necessary to branch commits. I didn't fully understand the git system :( .  
What are the reasons for not being able to merge, technical? I will be at my computer soon and will try to cancel the last 3 commits.

I was just redesigning the SortH tool, the case when sorting took 180 seconds, now it takes 2.5 seconds, that is increased in x70 times, and also works in synchronization mode. The only thing now is to redo the relocation and the tool will play with new colors.

I hope that you will not disappear, we can breathe new life into this tool.

**Comment by franMarz** [comment]
Thank you for the patch

**Pull request merged**
