### PR TITLE
Refactor: Align

### PR DESCRIPTION
**Pull request by Oxicid**
- Speedup (100 monkey) x2, and up to 8 times if the object is partially selected.
- In sync mode the speed can reach up to 100 times.
- There are no unnecessary updates of the object, and this is another speedup.
- The code is more grouped. 
- More checks for errors.

### CODE REVIEW

**Comment by franMarz** [comment]
Love to see that we're getting away from the multi_object_loop, well done.
I'll merge it as it is. bmeshes_refcount_safe is not accessed though, is it really needed?

**Comment by Oxicid** [comment]
@franMarz Yes, it is necessary, otherwise there are no links left and bmesh kind of frees up and you get wrong results, most importantly without errors, which at first may take you by surprise, you can see for yourself by simply deleting list

**Comment by franMarz** [comment]
Interesting, so saving bmeshes in a list is enough to work with different objects as long as you use the corresponding uvlayer when manipulating the UVs... And if you need to manipulate the meshes then you use the corresponding bmesh explicitly. So we should be able to adapt all operators to avoid the multi_object_loop now?

**Comment by Oxicid** [comment]
@franMarz  Bmesh does not need to be saved if its elements are not used outside the loop in which it was created, python is so organized that it understands when the loop iteration is finished and immediately decrement refcount and if it is zero, the deallocation method is called immediately (memory manager divides objects into 3(4?) parts, according to the frequency of checking references to call deallocations, 1) often it is an immediate check after exiting the namespace 2) a bit less often - when there were several checks (without zero refcount) 3) even less often, it is after multiple attempts of deallocations 4) and I may be wrong, even less often for global variables ).
There are also such things as if an object weighs 512 bytes (or 256?), it is stored in the arena (which in turn also has cells of smaller bytes), in pre-reserved memory (it avoids frequent requests from OS).

There's a lot more to it, so I'm trying to avoid various python calls, creating unnecessary lists with elements, etc. :)

Yes, all operators can be played without multi_loop, which is sometimes a little more difficult due to working with structures and storing data

**Comment by franMarz** [comment]
Thank you for the in-depth explanation, really appreciated.

**Pull request merged**
