### PR TITLE
Rotate 90: Access Rotate operator in sync mode

### PR DESCRIPTION
**Pull request by Oxicid**
The operator in sync mode works a little differently (islands are affected in extend mode). Also, I did not add the code for calculating the median point, I don't see the point in it

### CODE REVIEW

**Comment by franMarz** [comment]
I've been working on UV Sync compatibility the past two days as well... I don't know whether this add any benefit over the new code, I find your solution maybe over complicated?

**Comment by Oxicid** [comment]
@franMarz What a great coincidence, how many years no one has done sync mode, and as soon as I had time and decided to finish writing the code, and as soon as you have already done it :)

**Comment by Oxicid** [comment]
Yes my variant is more complicated, but less artefactual in vertex and edge mode, and also extend selected allows to level the absence of island mode in sync mode

**Comment by franMarz** [comment]
Yeah, I was confused too. I wasted some time the last day adjusting Centralize because I needed it for an ongoing project. You can compare my code with yours and see how different they are. Then, I adjusted other tools.

I'm not merging this, I'll adopt a different approach. I'll commit it to master now.

**Pull request closed without merging**
