### PR TITLE
Uv unwrap

### PR DESCRIPTION
**Pull request by BenjaminSauder**
Hi there,

this patch adds a new operator called 'unwrap' to the uv-layout area.
grafik

if you click unwrap -> the selected uvs get unwrapped again.
grafik

So this makes it really easy to reunwrap some parts if needed. As doing this manually in vanilla blender can be quite the chore..

I also added a simple u or v constrain to the operation, as such it will only change either the x/y values. This is quite handy when working with trim sheets or strips in general.
 
The icon is just something I quickly put together..

---

I stumbled over this ticket [https://developer.blender.org/T78394](https://developer.blender.org/T78394) - and thought this is would be actually quite doable in python already - so here we are.

## On a highlevel the tools does this:

1. invert selection
2. pin uvs
3. create seams from islands
3. call blender uv unwrap
4. restore selections / pins / seams

The tricky thing is, that blender always repacks the uvs after unwrap, so if you select a whole uv shell it gets moved around...
So there is a bit code which tries to handle this case.. not always successfully tho.

---

Best would probably to also submit a patch to blender itself to make the packing of the uv's optional - seemed quite easy, the operator just would need another property to see if it should pack.. but ..I dont have the blender dev stuff setup at the moment.

--

So please give it a try - and let me know what you think 🥂

### CODE REVIEW

**Comment by TitusLVR** [comment]
Nice, super useful and how easy to use. Checked - it works.

**Comment by TitusLVR** [comment]
@SavMartin Please, please add this to the main branch, this feature is a huge time saver.
@BenjaminSauder  Could you code another operator which does next for selected faces( or for visible faces in UV editor):
1 - pin active face verts 
2 - Unwrap
3 - remove pin for verts
actually its same as you have now but inverted :)) 
PS: it could be "I" button next to unwrap or on "ALT" event for unwrap button.
Many thanks.

**Comment by franMarz** [comment]
Sorry guys but I don't have a lot of time. I'll try to review and add this during Christmas.

**Comment by BenjaminSauder** [comment]
@franMarz no problem ;)

i used it in the meantime every now and then, and sometimes it shows weird behaviour... guess next time I encounter it, I should save the model... just wanted to note that apparently there are still issues.. :/

**Comment by franMarz** [comment]
I'll have that in mind. Thank you.

**Comment by franMarz** [comment]
I have no time recently. I think I'm going to merge this, but if there is any issue report, I hope you can manage it. This would go into the next release then.

**Pull request merged**
